/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "ID2ZwQcfxhUQ5yNDfE1ALGA",
        engine: "mysql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-058cc2448a7d0c652",
            securityGroupIds: [
                "sg-09742e9aef3eef793"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-05155a7be3401218f",
                    availabilityZone: "ap-southeast-2b"
                },
                {
                    subnetId: "subnet-0d9343e6c06d79425",
                    availabilityZone: "ap-southeast-2a"
                },
                {
                    subnetId: "subnet-0b7effccaa68b5bed",
                    availabilityZone: "ap-southeast-2c"
                }
            ]
        }
    }
}).schema({
    "uv_skin_data": a.model({
        id: a.integer().required(),
        fitzpatrick_phototype: a.string(),
        phenotype: a.string(),
        epidermal_eumelanin: a.string(),
        cutaneous_response_to_uv: a.string(),
        med_mj_cm2: a.string(),
        cancer_risk_out_of_4: a.string()
    }).identifier([
        "id"
    ]).authorization(allow => [allow.publicApiKey().to(["read"])])
});
